# Generated by Django 4.2.7 on 2024-01-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('seller_startig_bid', models.IntegerField()),
                ('last_ending_bid', models.IntegerField()),
                ('car_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_user', models.CharField(max_length=220)),
                ('last_bidding_total', models.IntegerField()),
                ('car_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id', models.IntegerField()),
                ('Model', models.CharField(max_length=100)),
                ('Engine', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=300)),
                ('OrginalPrice', models.CharField(max_length=100)),
                ('FuelType', models.CharField(max_length=300)),
                ('FuelEfficiency', models.CharField(max_length=300)),
                ('Features', models.CharField(max_length=300)),
                ('Safety', models.CharField(max_length=300)),
                ('InsuranceValidDate', models.CharField(max_length=100)),
                ('PUCCValidDate', models.CharField(max_length=100)),
                ('FitnessValidDate', models.CharField(max_length=100)),
                ('frount_image', models.ImageField(upload_to='images/')),
                ('Images', models.ImageField(upload_to='images/')),
                ('decription', models.TextField()),
                ('checkBox', models.BooleanField(default=False)),
                ('finishing_time', models.TimeField(default='00:00:00')),
                ('starting_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('car_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=220)),
                ('last_name', models.CharField(max_length=220)),
                ('user_name', models.CharField(max_length=220)),
                ('mail', models.CharField(max_length=220)),
                ('phNo', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
