# Generated by Django 5.0.1 on 2024-01-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biddings',
            old_name='last_ending_bid',
            new_name='starting_bid_time',
        ),
    ]
