# Generated by Django 5.0.1 on 2024-01-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0002_rename_last_ending_bid_biddings_starting_bid_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='Images',
        ),
        migrations.AlterField(
            model_name='biddings',
            name='seller_startig_bid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='biddings',
            name='starting_bid_time',
            field=models.DateTimeField(),
        ),
    ]
