# Generated by Django 4.2.7 on 2024-01-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0003_remove_carmodel_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='StartingPrice',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
