# Generated by Django 5.0.1 on 2024-01-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0004_carmodel_startingprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='finishing_time',
            field=models.DateTimeField(),
        ),
    ]
