# Generated by Django 5.0.1 on 2024-01-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0005_auctionitem_alter_carmodel_finishing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='userImagr',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
