# Generated by Django 5.0.1 on 2024-02-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0006_usermodel_address_usermodel_userimagr'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='Middle_name',
            field=models.CharField(default=1, max_length=220),
            preserve_default=False,
        ),
    ]
