# Generated by Django 5.0.1 on 2024-02-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0007_usermodel_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='userImagr',
            new_name='userImage',
        ),
    ]
