# Generated by Django 4.2.7 on 2024-02-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0008_rename_userimagr_usermodel_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='phNo',
        ),
    ]
