# Generated by Django 4.2.7 on 2024-02-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0009_remove_usermodel_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
