# Generated by Django 4.2.7 on 2024-02-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0010_usermodel_phno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='phNo',
        ),
    ]
