# Generated by Django 4.2.7 on 2024-02-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0011_remove_usermodel_phno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionItem',
        ),
    ]
