# Generated by Django 4.2.7 on 2024-02-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0012_delete_auctionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='Middle_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phnum',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
