# Generated by Django 4.2.7 on 2024-03-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0013_remove_usermodel_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phnum',
            field=models.IntegerField(),
        ),
    ]
