# Generated by Django 4.2.7 on 2024-03-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVista', '0014_alter_usermodel_phnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phnum',
            field=models.IntegerField(max_length=20),
        ),
    ]
